config = {
    "WINDOW_WIDTH": 1000,
    "WINDOW_HEIGHT": 600,
    "SIMULATION_WIDTH": 800,
    "SIMULATION_CENTER": (0, 0),
    "FORM_WIDTH": 200,
    "ROAD_WIDTH": 200,
    "UI_ELEMENTS_SPACING": 5,
    "VEHICLE_WIDTH": 20,
    "VEHICLE_SPACING": 20,
    "VEHICLE_SPEED": 2,
    "TURNING_SPEED": 0.05,
    "LIGHT_RADIUS": 10,
    "LIGHT_LIMIT": 50,
    "YELLOW_LIGHT_TIME": 0.5,
    "RED_LIGHT_TIME": 8.9,
    "DEFAULT_GREEN_NORTH_LIGHT_TIME": 5,
    "DEFAULT_GREEN_SOUTH_LIGHT_TIME": 5,
    "DEFAULT_GREEN_EAST_LIGHT_TIME": 5,
    "DEFAULT_GREEN_WEST_LIGHT_TIME": 5,
    "NORTH_TITLE": "R",
    "SOUTH_TITLE": "Parque de las aguas",
    "EAST_TITLE": "Glorieta",
    "WEST_TITLE": "Sanitas",
    "TRAFFIC_LIGHTS_ORDER": {1: "E", 2: "W", 3: "S", 4: "N"},
    "VEHICLES_ASSETS_PATH": "assets/vehicles",
}
WHITE = (255, 255, 255)
GRAY = (50, 50, 50)
RED = (200, 0, 0)
GREEN = (0, 200, 0)
BLUE = (0, 0, 255)
YELLOW = (200, 200, 0)
